### ISSUE TITLE
gpg key error

### ISSUE THREAD

**Issue by GHGautamGH** [saltstack-formulas/cassandra-formula#1]
Hi,

Getting the below error when trying to apply the state. 

          ID: cassandra
    Function: pkgrepo.managed
        Name: deb http://www.apache.org/dist/cassandra/debian 37x main
      Result: False
     Comment: Failed to configure repo 'deb http://www.apache.org/dist/cassandra/debian 37x main': Error: key retrieval failed: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.cs5vAtwC3J --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/openjdk-r-ppa.gpg --keyserver pgp.mit.edu --logger-fd 1 --recv-keys 0353B12C
              gpgkeys: HTTP fetch error 56: Recv failure: Connection reset by peer
              gpg: requesting key 0353B12C from hkp server pgp.mit.edu
              gpg: no valid OpenPGP data found.
              gpg: key 0353B12C: no valid user IDs
              gpg: this may be caused by a missing self-signature
              gpg: Total number processed: 1
              gpg:           w/o user IDs: 1
     Started: 12:48:14.278024
    Duration: 2851.808 ms

My OS is "Ubuntu 14.04.5"

Any suggestions?

**Comment by kpostrup** [comment]
Hi 
I have added support for specifying GPG keyserver and version, and also updated the template to support version 39x. I belive this fixes your issue.

See commit: b3fb191cb667a5ffad081c844167298eb95b347a.
